[[dependency]]
# This file is used to install the pip dependencies for the aiq extension.
python = "../_build/target-deps/python"
packages = [
    "aiqtoolkit==1.1.0",
    "aiqtoolkit-langchain==1.1.0",
    "source/modules/aiq/lc_agent_aiq",
    "source/modules/agents/planning",

    "MarkupSafe==3.0.2",
    "aioboto3==14.3.0",
    "aiobotocore==2.22.0",
    "aioitertools==0.12.0",
    "aiosqlite==0.21.0",
    "appdirs==1.4.4",
    "boto3==1.37.35",
    "botocore==1.38.17",
    "cachetools==5.5.2",
    "cffi==1.17.1",
    "cryptography==44.0.2",
    "dill==0.3.8",
    "diskcache==5.6.3",
    "et_xmlfile==2.0.0",
    "expandvars==1.0.0",
    "fsspec==2024.12.0",
    "graphql_core==3.2.6",
    "grpc_interceptor==0.15.4",
    "grpcio==1.67.1",
    "httptools==0.6.4",
    "jinja2==3.1.6",
    "jmespath==1.0.1",
    "joblib==1.4.2",
    "jsonpath_ng==1.7.0",
    "langchain-milvus~=0.1.8",
    "langgraph-checkpoint==2.0.24",
    "langgraph-prebuilt==0.1.8",
    "langgraph-sdk==0.1.61",
    "langgraph==0.2.76",
    "mako==1.3.10",
    "markdown_it_py==3.0.0",
    "mcp==1.6.0",
    "mdurl==0.1.2",
    "multiprocess==0.70.16",
    "nest_asyncio==1.6.0",
    "networkx==3.4.2",
    "openinference_instrumentation==0.1.27",
    "openinference_semantic_conventions==0.1.17",
    "openpyxl==3.1.5",
    "ormsgpack==1.9.1",
    "pandas==2.2.3",
    "pkginfo==1.12.1.2",
    "ply==3.11",
    "protobuf==5.29.4",
    "psutil==7.0.0",
    "pyarrow==19.0.1",
    "pycparser==2.22",
    "pygments==2.19.1",
    "pymilvus==2.5.6",
    "python_dateutil==2.9.0.post0",
    "python_multipart==0.0.20",
    "pytz==2025.2",
    "ragas==0.2.14",
    "rich==13.9.4",
    "s3transfer==0.11.4",
    "scikit_learn==1.6.1",
    "scipy==1.15.2",
    "setuptools==78.1.0",
    "six==1.17.0",
    "sniffio==1.3.1",
    "soupsieve==2.6",
    "sqlean.py==3.47.0",
    "sse_starlette==2.2.1",
    "strawberry_graphql==0.243.1",
    "threadpoolctl==3.6.0",
    "tzdata==2025.2",
    "ujson==5.10.0",
    "websockets==15.0.1",
    "wikipedia==1.4.0",
    "wrapt==1.17.2",
    "xxhash==3.5.0",
    "zipp==3.21.0",
    "colorama",
]
extra_args = ["--no-deps", "--no-cache-dir", "--force-reinstall", "--upgrade", "--ignore-installed", "--use-deprecated=legacy-resolver"]
target = "../_build/target-deps/pip_aiq_prebundle"
platforms = ["*"]
download_only = false
append_to_install_folder = true
gather_licenses_path = "../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
